try this

diff --git a/.github/workflows/install_self/action.yml b/.github/workflows/install_self/action.yml
--- a/.github/workflows/install_self/action.yml
+++ b/.github/workflows/install_self/action.yml
@@ -12,19 +12,17 @@ runs:
       with:
         python-version: ${{ inputs.python-version }}
     - name: Install Dependencies with Retry
+      shell: bash
       run: |
         max_attempts=5
         sleep_seconds=10
         attempt_num=1
-        until timeout $sleep_seconds pip install . || [[ $attempt_num -eq $max_attempts ]]
-        do
+        until pip install .; do
           echo "Attempt $attempt_num of $max_attempts failed! Trying again in $sleep_seconds seconds..."
           sleep $sleep_seconds
           ((attempt_num++))
+          if [[ $attempt_num -eq $max_attempts ]]; then
+            echo "All $max_attempts attempts have failed!"
+            exit 1
+          fi
         done
-
-        if [[ $attempt_num -eq $max_attempts ]]; then
-          echo "All $max_attempts attempts have failed!"
-          exit 1
-        fi
-      shell: bash
