try this

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,10 +21,21 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - name: Install Self
-      uses: ./.github/actions/install_self@dev
-      with:
-        python-version: ${{ matrix.python-version }}
+    - name: Install Dependencies with Retry
+      shell: bash
+      run: |
+        max_attempts=5
+        sleep_seconds=10
+        attempt_num=1
+        until pip install .; do
+          echo "Attempt $attempt_num of $max_attempts failed! Trying again in $sleep_seconds seconds..."
+          sleep $sleep_seconds
+          ((attempt_num++))
+          if [[ $attempt_num -eq $max_attempts ]]; then
+            echo "All $max_attempts attempts have failed!"
+            exit 1
+          fi
+        done
 
     - name: Install Test Dependencies
       run: |
@@ -48,10 +59,21 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - name: Install Self
-      uses: ./.github/actions/install_self@dev
-      with:
-        python-version: ${{ matrix.python-version }}
+    - name: Install Dependencies with Retry
+      shell: bash
+      run: |
+        max_attempts=5
+        sleep_seconds=10
+        attempt_num=1
+        until pip install .; do
+          echo "Attempt $attempt_num of $max_attempts failed! Trying again in $sleep_seconds seconds..."
+          sleep $sleep_seconds
+          ((attempt_num++))
+          if [[ $attempt_num -eq $max_attempts ]]; then
+            echo "All $max_attempts attempts have failed!"
+            exit 1
+          fi
+        done
 
     - name: Coverage
       env:
